
//! Autogenerated weights for `pallet_commitment`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-05-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`,
//! HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Naveens-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/frame-suite-runtime/frame_suite_runtime.wasm
// --pallet
// pallet_commitment
// --extrinsic
// *
// --template
// pallets/.maintain/frame-weight-template.hbs
// --output
// pallets/commitment/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_commitment`.
pub trait WeightInfo {
fn deposit_reserve() -> Weight;
fn withdraw_reserve() -> Weight;
fn withdraw_reserve_partial() -> Weight;
fn inspect_digest_model() -> Weight;
fn inspect_commit_value() -> Weight;
fn inspect_index_value() -> Weight;
fn inspect_entry_value() -> Weight;
fn inspect_entries_value() -> Weight;
fn inspect_pool_value() -> Weight;
fn inspect_slot_value() -> Weight;
fn inspect_slots_value() -> Weight;
fn inspect_pool_commission() -> Weight;
fn inspect_pool_manager() -> Weight;
fn inspect_asset_to_issue() -> Weight;
fn inspect_asset_to_reap() -> Weight;
fn inspect_reason_value() -> Weight;
}

/// Weights for `pallet_commitment` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
                impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        fn deposit_reserve() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 33_000_000 picoseconds.
                        Weight::from_parts(36_000_000,
                        3573)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        fn withdraw_reserve() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 35_000_000 picoseconds.
                        Weight::from_parts(37_000_000,
                        3573)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        fn withdraw_reserve_partial() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 35_000_000 picoseconds.
                        Weight::from_parts(37_000_000,
                        3573)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_digest_model() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `206`
                        // Estimated: `3694`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        3694)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_commit_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `371`
                        // Estimated: `5065`
                        // Minimum execution time: 28_000_000 picoseconds.
                        Weight::from_parts(30_000_000,
                        5065)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        }
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:2 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_index_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1035`
                        // Estimated: `11757`
                        // Minimum execution time: 65_000_000 picoseconds.
                        Weight::from_parts(68_000_000,
                        11757)
                        .saturating_add(T::DbWeight::get().reads(6_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:1 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_entry_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `840`
                        // Estimated: `11757`
                        // Minimum execution time: 37_000_000 picoseconds.
                        Weight::from_parts(38_000_000,
                        11757)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:2 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_entries_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1035`
                        // Estimated: `11757`
                        // Minimum execution time: 64_000_000 picoseconds.
                        Weight::from_parts(66_000_000,
                        11757)
                        .saturating_add(T::DbWeight::get().reads(6_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_pool_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 41_000_000 picoseconds.
                        Weight::from_parts(44_000_000,
                        21799)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_slot_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 47_000_000 picoseconds.
                        Weight::from_parts(49_000_000,
                        21799)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_slots_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 82_000_000 picoseconds.
                        Weight::from_parts(85_000_000,
                        21799)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        fn inspect_pool_commission() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `521`
                        // Estimated: `21799`
                        // Minimum execution time: 11_000_000 picoseconds.
                        Weight::from_parts(12_000_000,
                        21799)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolManager` (r:1 w:0)
                        /// Proof: `Commitment::PoolManager` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
                        fn inspect_pool_manager() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `392`
                        // Estimated: `21799`
                        // Minimum execution time: 14_000_000 picoseconds.
                        Weight::from_parts(15_000_000,
                        21799)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        }
                        /// Storage: `Commitment::AssetToIssue` (r:1 w:0)
                        /// Proof: `Commitment::AssetToIssue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        fn inspect_asset_to_issue() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `123`
                        // Estimated: `1501`
                        // Minimum execution time: 6_000_000 picoseconds.
                        Weight::from_parts(7_000_000,
                        1501)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::AssetToReap` (r:1 w:0)
                        /// Proof: `Commitment::AssetToReap` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        fn inspect_asset_to_reap() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `180`
                        // Estimated: `1501`
                        // Minimum execution time: 7_000_000 picoseconds.
                        Weight::from_parts(8_000_000,
                        1501)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::ReasonValue` (r:1 w:0)
                        /// Proof: `Commitment::ReasonValue` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
                        fn inspect_reason_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `199`
                        // Estimated: `3499`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        3499)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        }
                        }

                        // For backwards compatibility and tests.
                        impl WeightInfo for () {
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        fn deposit_reserve() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 33_000_000 picoseconds.
                        Weight::from_parts(36_000_000,
                        3573)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        fn withdraw_reserve() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 35_000_000 picoseconds.
                        Weight::from_parts(37_000_000,
                        3573)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Xp::ReservedXpOf` (r:1 w:1)
                        /// Proof: `Xp::ReservedXpOf` (`max_values`: None, `max_size`: Some(67), added: 2542, mode: `MaxEncodedLen`)
                        /// Storage: `Xp::XpOf` (r:1 w:1)
                        /// Proof: `Xp::XpOf` (`max_values`: None, `max_size`: Some(108), added: 2583, mode: `MaxEncodedLen`)
                        fn withdraw_reserve_partial() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1384`
                        // Estimated: `3573`
                        // Minimum execution time: 35_000_000 picoseconds.
                        Weight::from_parts(37_000_000,
                        3573)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
                        }
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_digest_model() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `206`
                        // Estimated: `3694`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        3694)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_commit_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `371`
                        // Estimated: `5065`
                        // Minimum execution time: 28_000_000 picoseconds.
                        Weight::from_parts(30_000_000,
                        5065)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        }
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:2 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_index_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1035`
                        // Estimated: `11757`
                        // Minimum execution time: 65_000_000 picoseconds.
                        Weight::from_parts(68_000_000,
                        11757)
                        .saturating_add(RocksDbWeight::get().reads(6_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:1 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_entry_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `840`
                        // Estimated: `11757`
                        // Minimum execution time: 37_000_000 picoseconds.
                        Weight::from_parts(38_000_000,
                        11757)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::IndexMap` (r:1 w:0)
                        /// Proof: `Commitment::IndexMap` (`max_values`: None, `max_size`: Some(8292), added: 10767, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::EntryMap` (r:2 w:0)
                        /// Proof: `Commitment::EntryMap` (`max_values`: None, `max_size`: Some(1663), added: 4138, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_entries_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1035`
                        // Estimated: `11757`
                        // Minimum execution time: 64_000_000 picoseconds.
                        Weight::from_parts(66_000_000,
                        11757)
                        .saturating_add(RocksDbWeight::get().reads(6_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_pool_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 41_000_000 picoseconds.
                        Weight::from_parts(44_000_000,
                        21799)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_slot_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 47_000_000 picoseconds.
                        Weight::from_parts(49_000_000,
                        21799)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:2 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        fn inspect_slots_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `958`
                        // Estimated: `21799`
                        // Minimum execution time: 82_000_000 picoseconds.
                        Weight::from_parts(85_000_000,
                        21799)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        fn inspect_pool_commission() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `521`
                        // Estimated: `21799`
                        // Minimum execution time: 11_000_000 picoseconds.
                        Weight::from_parts(12_000_000,
                        21799)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::PoolMap` (r:1 w:0)
                        /// Proof: `Commitment::PoolMap` (`max_values`: None, `max_size`: Some(18334), added: 20809, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::PoolManager` (r:1 w:0)
                        /// Proof: `Commitment::PoolManager` (`max_values`: None, `max_size`: Some(98), added: 2573, mode: `MaxEncodedLen`)
                        fn inspect_pool_manager() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `392`
                        // Estimated: `21799`
                        // Minimum execution time: 14_000_000 picoseconds.
                        Weight::from_parts(15_000_000,
                        21799)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        }
                        /// Storage: `Commitment::AssetToIssue` (r:1 w:0)
                        /// Proof: `Commitment::AssetToIssue` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        fn inspect_asset_to_issue() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `123`
                        // Estimated: `1501`
                        // Minimum execution time: 6_000_000 picoseconds.
                        Weight::from_parts(7_000_000,
                        1501)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::AssetToReap` (r:1 w:0)
                        /// Proof: `Commitment::AssetToReap` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        fn inspect_asset_to_reap() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `180`
                        // Estimated: `1501`
                        // Minimum execution time: 7_000_000 picoseconds.
                        Weight::from_parts(8_000_000,
                        1501)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        }
                        /// Storage: `Commitment::ReasonValue` (r:1 w:0)
                        /// Proof: `Commitment::ReasonValue` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
                        fn inspect_reason_value() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `199`
                        // Estimated: `3499`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        3499)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        }
                        }