
//! Autogenerated weights for `pallet_chain_manager`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-05-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`,
//! HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Naveens-MacBook-Air.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/frame-suite-runtime/frame_suite_runtime.wasm
// --pallet
// pallet_chain_manager
// --extrinsic
// *
// --template
// pallets/.maintain/frame-weight-template.hbs
// --output
// pallets/chain-manager/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_chain_manager`.
pub trait WeightInfo {
fn validate() -> Weight;
fn chill() -> Weight;
fn declare() -> Weight;
fn elect() -> Weight;
fn force_allow_affidavits() -> Weight;
fn force_affidavit_begins_at() -> Weight;
fn force_affidavit_ends_at() -> Weight;
fn force_election_begins_at() -> Weight;
fn force_election_runner_points_upgrade() -> Weight;
fn force_validate_tx_priority() -> Weight;
fn force_election_tx_priority() -> Weight;
fn force_affidavit_tx_priority() -> Weight;
fn force_finality_after() -> Weight;
fn force_finality_ticks() -> Weight;
fn inspect_elects() -> Weight;
fn prepare_validation_payload() -> Weight;
fn inspect_affidavit() -> Weight;
fn on_offence(n: u32, ) -> Weight;
fn on_initialize_with_author() -> Weight;
}

/// Weights for `pallet_chain_manager` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
                impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinCollateral` (r:1 w:0)
                        /// Proof: `Authors::MinCollateral` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        fn validate() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1075`
                        // Estimated: `5065`
                        // Minimum execution time: 45_000_000 picoseconds.
                        Weight::from_parts(48_000_000,
                        5065)
                        .saturating_add(T::DbWeight::get().reads(5_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Session::Validators` (r:1 w:0)
                        /// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:2 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn chill() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `844`
                        // Estimated: `44039`
                        // Minimum execution time: 42_000_000 picoseconds.
                        Weight::from_parts(45_000_000,
                        44039)
                        .saturating_add(T::DbWeight::get().reads(9_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AllowAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AllowAffidavits` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinCollateral` (r:1 w:0)
                        /// Proof: `Authors::MinCollateral` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorFunders` (r:1 w:0)
                        /// Proof: `Authors::AuthorFunders` (`max_values`: None, `max_size`: Some(161), added: 2636, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:0 w:1)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn declare() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1281`
                        // Estimated: `5065`
                        // Minimum execution time: 78_000_000 picoseconds.
                        Weight::from_parts(82_000_000,
                        5065)
                        .saturating_add(T::DbWeight::get().reads(11_u64))
                        .saturating_add(T::DbWeight::get().writes(2_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::ElectionBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::ElectionBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:12 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinElected` (r:1 w:0)
                        /// Proof: `Authors::MinElected` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::ForceMaxElected` (r:1 w:0)
                        /// Proof: `Authors::ForceMaxElected` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::Elected` (r:12 w:11)
                        /// Proof: `Authors::Elected` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::ElectsPreparedBy` (r:0 w:1)
                        /// Proof: `ChainManager::ElectsPreparedBy` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::RecentElectedOn` (r:0 w:1)
                        /// Proof: `Authors::RecentElectedOn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn elect() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1718`
                        // Estimated: `517578`
                        // Minimum execution time: 149_000_000 picoseconds.
                        Weight::from_parts(162_000_000,
                        517578)
                        .saturating_add(T::DbWeight::get().reads(32_u64))
                        .saturating_add(T::DbWeight::get().writes(13_u64))
                        }
                        /// Storage: `ChainManager::AllowAffidavits` (r:0 w:1)
                        /// Proof: `ChainManager::AllowAffidavits` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        fn force_allow_affidavits() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_affidavit_begins_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `277`
                        // Estimated: `1489`
                        // Minimum execution time: 11_000_000 picoseconds.
                        Weight::from_parts(12_000_000,
                        1489)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_affidavit_ends_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `261`
                        // Estimated: `1489`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        1489)
                        .saturating_add(T::DbWeight::get().reads(1_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionBeginsAt` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_election_begins_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionRunnerPointsUpgrade` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionRunnerPointsUpgrade` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
                        fn force_election_runner_points_upgrade() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ValidateTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::ValidateTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_validate_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_election_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_affidavit_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::FinalityAfter` (r:0 w:1)
                        /// Proof: `ChainManager::FinalityAfter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_finality_after() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::FinalityTicks` (r:0 w:1)
                        /// Proof: `ChainManager::FinalityTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_finality_ticks() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        /// Storage: `Authors::RecentElectedOn` (r:1 w:0)
                        /// Proof: `Authors::RecentElectedOn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::Elected` (r:11 w:0)
                        /// Proof: `Authors::Elected` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
                        fn inspect_elects() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `879`
                        // Estimated: `28963`
                        // Minimum execution time: 46_000_000 picoseconds.
                        Weight::from_parts(48_000_000,
                        28963)
                        .saturating_add(T::DbWeight::get().reads(12_u64))
                        }
                        /// Storage: `Timestamp::Now` (r:1 w:0)
                        /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        /// Storage: `System::BlockHash` (r:1 w:0)
                        /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::FinalityAfter` (r:1 w:0)
                        /// Proof: `ChainManager::FinalityAfter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::FinalityTicks` (r:1 w:0)
                        /// Proof: `ChainManager::FinalityTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn prepare_validation_payload() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `817`
                        // Estimated: `3509`
                        // Minimum execution time: 1_932_000_000 picoseconds.
                        Weight::from_parts(11_371_000_000,
                        3509)
                        .saturating_add(T::DbWeight::get().reads(4_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn inspect_affidavit() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `519`
                        // Estimated: `44039`
                        // Minimum execution time: 21_000_000 picoseconds.
                        Weight::from_parts(23_000_000,
                        44039)
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        }
                        /// Storage: `Authors::AuthorsMap` (r:100 w:100)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::IncreaseProbationBy` (r:1 w:0)
                        /// Proof: `Authors::IncreaseProbationBy` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::PenaltiesBuffer` (r:1 w:0)
                        /// Proof: `Authors::PenaltiesBuffer` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorPenalties` (r:100 w:100)
                        /// Proof: `Authors::AuthorPenalties` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::PenaltiesUntil` (r:1 w:1)
                        /// Proof: `Authors::PenaltiesUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// The range of component `n` is `[1, 100]`.
                        fn on_offence(n: u32, ) -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `482 + n * (102 ±0)`
                        // Estimated: `1489 + n * (2602 ±0)`
                        // Minimum execution time: 33_000_000 picoseconds.
                        Weight::from_parts(10_220_822,
                        1489)
                        // Standard Error: 70_461
                        .saturating_add(Weight::from_parts(21_872_314,
                        0).saturating_mul(n.into()))
                        .saturating_add(T::DbWeight::get().reads(3_u64))
                        .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
                        .saturating_add(Weight::from_parts(0, 2602).saturating_mul(n.into()))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::BlockPointsStore` (r:1 w:1)
                        /// Proof: `ChainManager::BlockPointsStore` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
                        fn on_initialize_with_author() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `261`
                        // Estimated: `3541`
                        // Minimum execution time: 13_000_000 picoseconds.
                        Weight::from_parts(15_000_000,
                        3541)
                        .saturating_add(T::DbWeight::get().reads(2_u64))
                        .saturating_add(T::DbWeight::get().writes(1_u64))
                        }
                        }

                        // For backwards compatibility and tests.
                        impl WeightInfo for () {
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinCollateral` (r:1 w:0)
                        /// Proof: `Authors::MinCollateral` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        fn validate() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1075`
                        // Estimated: `5065`
                        // Minimum execution time: 45_000_000 picoseconds.
                        Weight::from_parts(48_000_000,
                        5065)
                        .saturating_add(RocksDbWeight::get().reads(5_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Session::Validators` (r:1 w:0)
                        /// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:2 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn chill() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `844`
                        // Estimated: `44039`
                        // Minimum execution time: 42_000_000 picoseconds.
                        Weight::from_parts(45_000_000,
                        44039)
                        .saturating_add(RocksDbWeight::get().reads(9_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:1)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AllowAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AllowAffidavits` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorsMap` (r:1 w:0)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::CommitMap` (r:1 w:0)
                        /// Proof: `Commitment::CommitMap` (`max_values`: None, `max_size`: Some(1600), added: 4075, mode: `MaxEncodedLen`)
                        /// Storage: `Commitment::DigestMap` (r:1 w:0)
                        /// Proof: `Commitment::DigestMap` (`max_values`: None, `max_size`: Some(229), added: 2704, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinCollateral` (r:1 w:0)
                        /// Proof: `Authors::MinCollateral` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorFunders` (r:1 w:0)
                        /// Proof: `Authors::AuthorFunders` (`max_values`: None, `max_size`: Some(161), added: 2636, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:0 w:1)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn declare() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1281`
                        // Estimated: `5065`
                        // Minimum execution time: 78_000_000 picoseconds.
                        Weight::from_parts(82_000_000,
                        5065)
                        .saturating_add(RocksDbWeight::get().reads(11_u64))
                        .saturating_add(RocksDbWeight::get().writes(2_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::SessionStartAt` (r:1 w:0)
                        /// Proof: `ChainManager::SessionStartAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::ElectionBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::ElectionBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:12 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::MinElected` (r:1 w:0)
                        /// Proof: `Authors::MinElected` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::ForceMaxElected` (r:1 w:0)
                        /// Proof: `Authors::ForceMaxElected` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::Elected` (r:12 w:11)
                        /// Proof: `Authors::Elected` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::ElectsPreparedBy` (r:0 w:1)
                        /// Proof: `ChainManager::ElectsPreparedBy` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::RecentElectedOn` (r:0 w:1)
                        /// Proof: `Authors::RecentElectedOn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn elect() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `1718`
                        // Estimated: `517578`
                        // Minimum execution time: 149_000_000 picoseconds.
                        Weight::from_parts(162_000_000,
                        517578)
                        .saturating_add(RocksDbWeight::get().reads(32_u64))
                        .saturating_add(RocksDbWeight::get().writes(13_u64))
                        }
                        /// Storage: `ChainManager::AllowAffidavits` (r:0 w:1)
                        /// Proof: `ChainManager::AllowAffidavits` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
                        fn force_allow_affidavits() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_affidavit_begins_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `277`
                        // Estimated: `1489`
                        // Minimum execution time: 11_000_000 picoseconds.
                        Weight::from_parts(12_000_000,
                        1489)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitBeginsAt` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitEndsAt` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitEndsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_affidavit_ends_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `261`
                        // Estimated: `1489`
                        // Minimum execution time: 9_000_000 picoseconds.
                        Weight::from_parts(10_000_000,
                        1489)
                        .saturating_add(RocksDbWeight::get().reads(1_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionBeginsAt` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionBeginsAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_election_begins_at() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionRunnerPointsUpgrade` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionRunnerPointsUpgrade` (`max_values`: Some(1), `max_size`: Some(9), added: 504, mode: `MaxEncodedLen`)
                        fn force_election_runner_points_upgrade() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ValidateTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::ValidateTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_validate_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::ElectionTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::ElectionTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_election_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::AffidavitTxPriority` (r:0 w:1)
                        /// Proof: `ChainManager::AffidavitTxPriority` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_affidavit_tx_priority() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::FinalityAfter` (r:0 w:1)
                        /// Proof: `ChainManager::FinalityAfter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        fn force_finality_after() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `ChainManager::FinalityTicks` (r:0 w:1)
                        /// Proof: `ChainManager::FinalityTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn force_finality_ticks() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `0`
                        // Estimated: `0`
                        // Minimum execution time: 4_000_000 picoseconds.
                        Weight::from_parts(5_000_000,
                        0)
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        /// Storage: `Authors::RecentElectedOn` (r:1 w:0)
                        /// Proof: `Authors::RecentElectedOn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::Elected` (r:11 w:0)
                        /// Proof: `Authors::Elected` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
                        fn inspect_elects() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `879`
                        // Estimated: `28963`
                        // Minimum execution time: 46_000_000 picoseconds.
                        Weight::from_parts(48_000_000,
                        28963)
                        .saturating_add(RocksDbWeight::get().reads(12_u64))
                        }
                        /// Storage: `Timestamp::Now` (r:1 w:0)
                        /// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        /// Storage: `System::BlockHash` (r:1 w:0)
                        /// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::FinalityAfter` (r:1 w:0)
                        /// Proof: `ChainManager::FinalityAfter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::FinalityTicks` (r:1 w:0)
                        /// Proof: `ChainManager::FinalityTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        fn prepare_validation_payload() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `817`
                        // Estimated: `3509`
                        // Minimum execution time: 1_932_000_000 picoseconds.
                        Weight::from_parts(11_371_000_000,
                        3509)
                        .saturating_add(RocksDbWeight::get().reads(4_u64))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AffidavitKeys` (r:1 w:0)
                        /// Proof: `ChainManager::AffidavitKeys` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::AuthorAffidavits` (r:1 w:0)
                        /// Proof: `ChainManager::AuthorAffidavits` (`max_values`: None, `max_size`: Some(40574), added: 43049, mode: `MaxEncodedLen`)
                        fn inspect_affidavit() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `519`
                        // Estimated: `44039`
                        // Minimum execution time: 21_000_000 picoseconds.
                        Weight::from_parts(23_000_000,
                        44039)
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        }
                        /// Storage: `Authors::AuthorsMap` (r:100 w:100)
                        /// Proof: `Authors::AuthorsMap` (`max_values`: None, `max_size`: Some(127), added: 2602, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::IncreaseProbationBy` (r:1 w:0)
                        /// Proof: `Authors::IncreaseProbationBy` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::PenaltiesBuffer` (r:1 w:0)
                        /// Proof: `Authors::PenaltiesBuffer` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::AuthorPenalties` (r:100 w:100)
                        /// Proof: `Authors::AuthorPenalties` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
                        /// Storage: `Authors::PenaltiesUntil` (r:1 w:1)
                        /// Proof: `Authors::PenaltiesUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// The range of component `n` is `[1, 100]`.
                        fn on_offence(n: u32, ) -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `482 + n * (102 ±0)`
                        // Estimated: `1489 + n * (2602 ±0)`
                        // Minimum execution time: 33_000_000 picoseconds.
                        Weight::from_parts(10_220_822,
                        1489)
                        // Standard Error: 70_461
                        .saturating_add(Weight::from_parts(21_872_314,
                        0).saturating_mul(n.into()))
                        .saturating_add(RocksDbWeight::get().reads(3_u64))
                        .saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n.into())))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        .saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
                        .saturating_add(Weight::from_parts(0, 2602).saturating_mul(n.into()))
                        }
                        /// Storage: `ChainManager::CurrentSession` (r:1 w:0)
                        /// Proof: `ChainManager::CurrentSession` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
                        /// Storage: `ChainManager::BlockPointsStore` (r:1 w:1)
                        /// Proof: `ChainManager::BlockPointsStore` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
                        fn on_initialize_with_author() -> Weight {
                        // Proof Size summary in bytes:
                        // Measured: `261`
                        // Estimated: `3541`
                        // Minimum execution time: 13_000_000 picoseconds.
                        Weight::from_parts(15_000_000,
                        3541)
                        .saturating_add(RocksDbWeight::get().reads(2_u64))
                        .saturating_add(RocksDbWeight::get().writes(1_u64))
                        }
                        }